---
title: "2024-08-07"
author: "MM Thomas"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidytuesdayR, tidyverse, stringr)
```

## Olympics Data

```{r intro-loook}
olym <- tt_load("2024-08-06")

df_o <- olym$olympics

```

```{r}

glimpse(df_o)

```

```{r}

df_o %>% 
  filter(between(year, 1900, 2016)) %>% 
  summarise(
    min_year = min(year),
    max_year = max(year)
  )

```

## Dotplot of which countries were in the Olympics each year

```{r}

p <- df_o %>% 
  filter(between(year, 1900, 1940) &
           str_detect(games, "Summer")) %>% 
  summarise(in_summer_games = 1, .by = c(year, noc)) %>% 
  arrange(year) %>% 
  distinct(noc, .keep_all = TRUE) %>% 
  mutate(index = row_number(), .by = year) %>% 
  ggplot(aes(x = year, fill = noc)) + 
  geom_dotplot(binwidth = 1, stackgroups = TRUE, binpositions = "bygroup",
               stackdir = "center") #+
  #guides(fill = "none")
  

p
```


```{r}

df_o_summarized <- df_o %>% 
  filter(between(year, 1900, 1940) &
           str_detect(games, "Summer")) %>% 
  summarise(in_summer_games = 1, .by = c(year, noc)) %>% 
  arrange(year) %>% 
  distinct(noc, .keep_all = TRUE) %>% 
  mutate(index = row_number(), .by = year) 

p <-  df_o_summarized %>% 
  ggplot(aes(x = year, y = index, label = noc)) + 
  geom_label(label.size = ) +
  labs(y = "", x = "Summer Olympics Year",
       title = "First Appearances in Summer Olympics: 1900-1940") +
  scale_x_continuous(breaks = unique(df_o_summarized$year)) +
  theme_bw() +
  theme(panel.grid.minor.x = element_blank())
  

p


```

```{r}

library(plotly)
ggplotly(p)


```



