---
title: "2024-08-07"
author: "MM Thomas"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidytuesdayR, tidyverse, stringr, gt, gtExtras)
```

## Olympics Data

```{r intro-loook}
monar <- tt_load("2024-08-20")
df_m <- monar$english_monarchs_marriages_df

```

```{r}

# df_m %>% 
#   mutate(king_age_nums = str_remove(king_age, "[^[:digit:]]+"),
#          king_age_numeric = as.numeric(king_age_nums)) %>% 
#   distinct(king_age,king_age_nums,king_age_numeric) %>% View() 

to_numeric <- function(x) as.numeric(str_remove(x, "[^[:digit:]]+"))

df_m_clean <- df_m %>%
  mutate(consort_name = str_replace(consort_name, "ick\\-Lueneburg\\-Celle",
                     "\\.\\.\\."),
         king_age_nums = str_remove(king_age, "[^[:digit:]]+"),
         king_age_numeric = as.numeric(king_age_nums),
         consort_age_numeric = to_numeric(consort_age),
         year = to_numeric(year_of_marriage)) 

```

```{r}

df_m_final <- df_m_clean %>% 
  filter(!is.na(king_age_numeric) & !is.na(consort_age_numeric)) %>% 
  mutate(king_name, consort_name, king_age_numeric, consort_age_numeric, year,
         `Age Diff` = king_age_numeric - consort_age_numeric, .keep = "used") %>% 
  rename(King = king_name, Consort = consort_name,
         `King Age` = king_age_numeric, `Consort Age` = consort_age_numeric, 
         Year = year) %>% 
  rowwise() %>% 
  mutate(`Age List`= list(c(`King Age`, `Consort Age`)))
  
# pivot_longer(cols = `Age Diff`) %>% 
  # group_by(King, Consort, `King Age`, `Consort Age`, Year, name) %>% 
  # summarise( = list(value))
  # View()

```


```{r}

# Add a horizontal line sparkline
gt_table <- df_m_final %>%
  gt() %>% 
  gt_plt_sparkline(
    column = `Age List`, # Column containing the data for the sparkline
    type = "default", # Specify the type of sparkline (line, bar, box, etc.)
    palette = c("grey70", "transparent", "grey60", 
                "black", "transparent"), # Color palette for the sparkline
    same_limit = TRUE # Whether to use the same y-axis limits for all sparklines
  ) %>% 
  cols_align(
    align = "center",
    columns = c(`King Age`, `Consort Age`, Year, `Age Diff`)
  ) %>% 
  cols_label(
    King = md("**King**"),
    Consort = md("**Consort (Wife???)**"),
    `King Age` = md("**King Age**"), 
    `Consort Age` = md("**Consort Age**"),
    Year = md("**Year**"),
    `Age Diff` = md("**Age Diff**"),
    `Age List` = md("**Age Plot**")
  ) %>% 
  opt_table_font(
    font = list(
       "serif"
    )
  )
   

# Display the table
gt_table

```

